In [3]:
import numpy as np

In [4]:
arr=np.array([1,23,33])

In [6]:
arr

array([ 1, 23, 33])

In [11]:
arr2=np.array([[1,23,33],[2,22,54]])
arr2

array([[ 1, 23, 33],
       [ 2, 22, 54]])

In [13]:
arr.ndim

1

In [15]:
arr2.ndim

2

In [22]:
arr3=np.array([[[1,23,33],[2,22,54],[5,6,8]],[[10,20,30],[25,22,55],[50,60,80]]])
arr3

array([[[ 1, 23, 33],
        [ 2, 22, 54],
        [ 5,  6,  8]],

       [[10, 20, 30],
        [25, 22, 55],
        [50, 60, 80]]])

In [24]:
arr3.ndim

3

In [27]:
arr[0:2]

array([ 1, 23])

In [29]:
arr2[0,2]#to pick 33

33

In [31]:
arr2[1,0:2]

array([ 2, 22])

In [33]:
arr3[0,1,2]

54

In [1]:
arr3[1,1,1:]

NameError: name 'arr3' is not defined

In [4]:
ar1=np.array([[10,20],[30,44]])
ar2=np.array([[11,22],[33,55]])
ar=np.concatenate((ar1,ar2))
ar

array([[10, 20],
       [30, 44],
       [11, 22],
       [33, 55]])

In [6]:
ar.ndim

2

In [8]:
ar.shape

(4, 2)

In [10]:
#Create Numpy arrays
temperature_data = np.array([25.3, 26.1, 24.8, 23.5, 27.2])
pressure_data = np.array([101.2, 100.8, 101.5, 100.2, 101.0])
humidity_data = np.array([55.2, 54.8, 56.5, 53.7, 55.9])

In [13]:
#Calculate the mean (average) for each quantity
avgtemp=np.mean(temperature_data)# both mean and average functions can be used
avgpres=np.average(pressure_data)
avghumid=np.average(humidity_data)
print(avgtemp,avgpres,avghumid)

25.380000000000003 100.94 55.21999999999999


In [15]:
#Calculate standard deviation
temp_std= np.std(temperature_data)
pressure_std= np.std(pressure_data)
humidity_std= np.std(humidity_data)
print(temp_std,pressure_std,humidity_std)

1.2416118556135003 0.43634848458542813 0.9579144011862429


In [19]:
#Calculate the max and min values
tempmax=np.max(temperature_data)
presmax=np.max(pressure_data)
humidmax=np.max(humidity_data)

tempmin=np.min(temperature_data)
presmin=np.min(pressure_data)
humidmin=np.min(humidity_data)
print(tempmax,presmax,humidmax,tempmin,presmin,humidmin)

27.2 101.5 56.5 23.5 100.2 53.7
